trigger:
  branches:
    include:
      - main

stages:
- stage: Run_Tests
  jobs:
  - job:  Run_Tests
    displayName: '  Run_Tests'
    pool: Default

    steps:
        - checkout: self 
          displayName: 'Checkout Repository'
          
        - task: CmdLine@2
          displayName: 'Launch MATLAB'
          inputs:
            script: |
             mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);[~,exitCode] = runprocess(Tasks = {'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|74194125-b632-41a1-b96d-b3364441277f', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|ced877ff-cfb8-4fa8-9bbf-aaa29b1d926b', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|d3a72cc8-687b-44ae-a909-7eff803b455b', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/OuterLoop_Control/test_cases/OuterLoop_Control_REQ_Based_Test.mldatx|51b0cb29-34f5-4c04-9104-4f3b0b48dda9', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/OuterLoop_Control/test_cases/OuterLoop_Control_REQ_Based_Test.mldatx|70d344b2-d65f-4872-9e4b-cef338e618a5', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/OuterLoop_Control/test_cases/OuterLoop_Control_REQ_Based_Test.mldatx|862932e4-be44-4f66-9abe-fb313da73c0d'}, Force = false, ExitInBatchMode = false, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);exit(exitCode);" 

        
        - task: CopyFiles@2
          displayName: 'Move desired artifacts to "temp" folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
                    03_Code/**
                    04_Results/AHRS_Voter/code_inspection/**
                    04_Results/AHRS_Voter/code_quality/**
                    04_Results/AHRS_Voter/coding_standards/**
                    04_Results/AHRS_Voter/design_error_detections/**
                    04_Results/AHRS_Voter/model_comparison/**
                    04_Results/AHRS_Voter/model_standards_results/**
                    04_Results/AHRS_Voter/system_design_description/**
                    04_Results/AHRS_Voter/webview/**
                    04_Results/Actuator_Control/code_inspection/**
                    04_Results/Actuator_Control/code_quality/**
                    04_Results/Actuator_Control/coding_standards/**
                    04_Results/Actuator_Control/design_error_detections/**
                    04_Results/Actuator_Control/model_comparison/**
                    04_Results/Actuator_Control/model_standards_results/**
                    04_Results/Actuator_Control/system_design_description/**
                    04_Results/Actuator_Control/webview/**
                    04_Results/Flight_Control/code_inspection/**
                    04_Results/Flight_Control/code_quality/**
                    04_Results/Flight_Control/coding_standards/**
                    04_Results/Flight_Control/design_error_detections/**
                    04_Results/Flight_Control/model_comparison/**
                    04_Results/Flight_Control/model_standards_results/**
                    04_Results/Flight_Control/system_design_description/**
                    04_Results/Flight_Control/webview/**
                    04_Results/InnerLoop_Control/code_inspection/**
                    04_Results/InnerLoop_Control/code_quality/**
                    04_Results/InnerLoop_Control/coding_standards/**
                    04_Results/InnerLoop_Control/design_error_detections/**
                    04_Results/InnerLoop_Control/model_comparison/**
                    04_Results/InnerLoop_Control/model_standards_results/**
                    04_Results/InnerLoop_Control/system_design_description/**
                    04_Results/InnerLoop_Control/webview/**
                    04_Results/OuterLoop_Control/code_inspection/**
                    04_Results/OuterLoop_Control/code_quality/**
                    04_Results/OuterLoop_Control/coding_standards/**
                    04_Results/OuterLoop_Control/design_error_detections/**
                    04_Results/OuterLoop_Control/model_comparison/**
                    04_Results/OuterLoop_Control/model_standards_results/**
                    04_Results/OuterLoop_Control/system_design_description/**
                    04_Results/OuterLoop_Control/webview/**
                    04_Results/test_results/**
                    derived/artifacts.dmr
            targetFolder: $(System.DefaultWorkingDirectory)/temp/
        
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/temp/
            artifact: 'padv_artifacts_5'
            publishLocation: 'pipeline' 