trigger:
  branches:
    include:
      - main

stages:
- stage: Restore_Cache
  jobs:
  - job: Restore_Cache
    displayName: 'Restore_Cache'
    pool: Default
    steps:
    - checkout: self
      displayName: 'Checkout Repository' 
    - task: Cache@2
      displayName: 'Restore Results Cache'
      inputs:
        key: 'working|testing'
        path: |
              $(System.DefaultWorkingDirectory)/04_Results
    - task: Cache@2
      displayName: 'Restore Derived Cache'
      inputs:
        key: 'working1|testing1'
        path: |
              $(System.DefaultWorkingDirectory)/derived   

    - script: |
        mkdir $(System.DefaultWorkingDirectory)/04_Results
      displayName: 'Create 04_Results Folder'
      continueOnError: true                 
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/04_Results/
        artifact: 'padv_artifacts_results'
        publishLocation: 'pipeline'
      condition: ne(variables['Cache.RestoreBuildInputs.result'], 'Restored')  
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/derived/
        artifact: 'padv_artifacts_derived'
        publishLocation: 'pipeline' 

- stage: Generate_Simulink_Web_View
  dependsOn: Restore_Cache
  jobs:
  - job: Generate_Simulink_Web_View
    displayName: 'Generate_Simulink_Web_View'
    pool: Default
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Results Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_results'
        targetPath: '$(System.DefaultWorkingDirectory)/04_Results'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Derived Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_derived'
        targetPath: '$(System.DefaultWorkingDirectory)/derived'  
    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
        script: |
          mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"

    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/04_Results/
        artifact: 'padv_artifacts_results1'
        publishLocation: 'pipeline' 
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/derived/
        artifact: 'padv_artifacts_derived1'
        publishLocation: 'pipeline'     

- stage: Check_Modeling_Standards 
  dependsOn: Generate_Simulink_Web_View            
  jobs:
  - job: Check_Modeling_Standards
    displayName: 'Check_Modeling_Standards'
    pool: Default
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Results Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_results1'
        targetPath: '$(System.DefaultWorkingDirectory)/04_Results'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Derived Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_derived1'
        targetPath: '$(System.DefaultWorkingDirectory)/derived'

    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
        script: |
         mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx', 'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx', 'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx', 'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx', 'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"

    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/04_Results/
        artifact: 'padv_artifacts_results2'
        publishLocation: 'pipeline' 
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/derived/
        artifact: 'padv_artifacts_derived2'
        publishLocation: 'pipeline'    

- stage: Detect_Design_Errors
  dependsOn: Check_Modeling_Standards 
  jobs:
  - job: Detect_Design_Errors  
    displayName: 'Detect_Design_Errors'
    pool: Default
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'     
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Results Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_results2'
        targetPath: '$(System.DefaultWorkingDirectory)/04_Results'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Derived Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_derived2'
        targetPath: '$(System.DefaultWorkingDirectory)/derived'
    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
       script: |
        mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx', 'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx', 'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx', 'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx', 'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"

    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/04_Results/
        artifact: '04Results'
        publishLocation: 'pipeline' 
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/derived/
        artifact: 'Derived'
        publishLocation: 'pipeline' 

- stage: Collect_Artifacts
  dependsOn: Detect_Design_Errors
  jobs:
  - job: Collect_Artifacts
    displayName: 'Collect_Artifacts'
    pool: Default
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifacts'
      inputs:
       artifactName: '04Results'
       downloadPath: $(System.DefaultWorkingDirectory)/04_Results
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifacts'
      inputs:
       artifactName: 'Derived'
       downloadPath: $(System.DefaultWorkingDirectory)/derived
      
    - task: Cache@2
      displayName: Save Cache
      inputs:
        key: 'work|test'
        path: |
              $(System.DefaultWorkingDirectory)/04_Results
    - task: Cache@2
      displayName: Save Cache
      inputs:
        key: 'work|test'
        path: |
              $(System.DefaultWorkingDirectory)/derived  
