trigger:
  branches:
    include:
      - main

stages:


- stage: Generate_Simulink_Web_View_AHRS_Voter

  
  jobs:
  - job: Generate_Simulink_Web_View_AHRS_Voter
    displayName: 'Generate_Simulink_Web_View_AHRS_Voter'
    pool: Default
    
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
      
    

- stage: Check_Modeling_Standards_AHRS_Voter
  dependsOn: Generate_Simulink_Web_View_AHRS_Voter    
  
  jobs:
  - job: Check_Modeling_Standards_AHRS_Voter
    displayName: 'Check_Modeling_Standards_AHRS_Voter'
    pool: Default
    
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'
      


- stage: Generate_Simulink_Web_View_Actuator_Control

  
  jobs:
  - job: Generate_Simulink_Web_View_Actuator_Control
    displayName: 'Generate_Simulink_Web_View_Actuator_Control'
    pool: Default
    
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
          
   
          
        

- stage: Check_Modeling_Standards_Actuator_Control
  dependsOn: Generate_Simulink_Web_View_Actuator_Control   
  
  jobs:
  - job: Check_Modeling_Standards_Actuator_Control
    displayName: 'Check_Modeling_Standards_Actuator_Control'
    pool: Default
    
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'
      
    


        
  