trigger:
  branches:
    include:
      - main

stages:
- stage: Generate_Simulink_Web_View

  jobs:
  - job: Generate_Simulink_Web_View
    pool: default
  

    steps:
        - checkout: self
          displayName: 'Checkout Repository'

        - checkout: self
          displayName: 'Checkout Repository2' 

  - job: Generate_Simulink_Web_View_second
    pool: default

    steps:
        - checkout: self
          displayName: 'Checkout Repository3'        



- stage: Check_Modelling

  jobs:
  - job: Check_Modeling
    pool: default

    steps:
        - checkout: self
          displayName: 'Checkout Repository'          