trigger:
  branches:
    include:
      - main

stages:
- stage: Sample_Stage
  displayName: Sample Stage
  jobs:
  - job: Sample_Job
    pool: Default  
    steps:
     - script: |
            echo "SAMPLE STAGE FOR PARALLEL PIPELINE"
 
  

- stage: Run_Tests_AHRS_Voter
  dependsOn:  Sample_Stage
  
  jobs:
  - job:  Run_Tests_AHRS_Voter
    displayName: '  Run_Tests_AHRS_Voter'
    pool: Default
    
    steps:
        - checkout: self 
          displayName: 'Checkout Repository'
          
            
        - task: CmdLine@2
          displayName: 'Launch MATLAB'
          inputs:
            script: |
             mw -using bslcicd matlab -nodesktop -logfile output.log  -batch "openProject(pwd);[~,exitCode] = runprocess(Tasks = {'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|ced877ff-cfb8-4fa8-9bbf-aaa29b1d926b', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|d3a72cc8-687b-44ae-a909-7eff803b455b', 'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|74194125-b632-41a1-b96d-b3364441277f'}, Force = false, ExitInBatchMode = false, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);exit(exitCode);" 

        
        - task: CopyFiles@2
          displayName: 'Move desired artifacts to "temp" folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
                    03_Code/**
                    04_Results/AHRS_Voter/code_inspection/**
                    04_Results/AHRS_Voter/code_quality/**
                    04_Results/AHRS_Voter/coding_standards/**
                    04_Results/AHRS_Voter/design_error_detections/**
                    04_Results/AHRS_Voter/model_comparison/**
                    04_Results/AHRS_Voter/model_standards_results/**
                    04_Results/AHRS_Voter/system_design_description/**
                    04_Results/AHRS_Voter/webview/**
                    04_Results/test_results/**
                    derived/artifacts.dmr
            targetFolder: $(System.DefaultWorkingDirectory)/temp/
        
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/temp/
            artifact: 'AHRS_Voter_padv_artifacts_5'
            publishLocation: 'pipeline' 

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: |
                padv_builtin_task_RunTestsPerTestCase_HLR_11_JUnit.xml
                padv_builtin_task_RunTestsPerTestCase_HLR_12_JUnit.xml
                padv_builtin_task_RunTestsPerTestCase_HLR_13_JUnit.xml   
            searchFolder: '$(System.DefaultWorkingDirectory)/04_Results/junit'
            

