trigger:
  branches:
    include:
      - main

stages:
- stage: Generate_Simulink_Web_View

  jobs:
  - job: Generate_Simulink_Web_View
    displayName: 'Generate_Simulink_Web_View'
    pool: Default

    steps:
        - checkout: self
          displayName: 'Checkout Repository'

        - script: |
              # Create a cache_folder in $(System.DefaultWorkingDirectory)
              mkdir $(System.DefaultWorkingDirectory)/cache_folder
          displayName: 'Create Cache Folder'   


        - task: CmdLine@2
          displayName: 'Launch MATLAB'
          inputs:
            script: |
              mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"
        
        - task: CopyFiles@2
          displayName: 'Move desired artifacts to "cache_folder" folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
                    derived/artifacts.dmr
                    04_Results/AHRS_Voter/webview/**
                    04_Results/Actuator_Control/webview/**
                    04_Results/Flight_Control/webview/**
                    04_Results/InnerLoop_Control/webview/**
                    04_Results/OuterLoop_Control/webview/**
                    04_Results/AHRS_Voter/model_standards_results/**
                    04_Results/Actuator_Control/model_standards_results/**
                    04_Results/Flight_Control/model_standards_results/**
                    04_Results/InnerLoop_Control/model_standards_results/**
                    04_Results/OuterLoop_Control/model_standards_results/**
            targetFolder: $(System.DefaultWorkingDirectory)/cache_folder/
        
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/derived/
            artifact: 'padv_artifacts_1'
            publishLocation: 'pipeline' 
            
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/04_Results/AHRS_Voter/webview/**
            artifact: 'padv_artifacts_2'
            publishLocation: 'pipeline' 
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/04_Results/Actuator_Control/webview/**
            artifact: 'padv_artifacts_3'
            publishLocation: 'pipeline' 
          
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/04_Results/Flight_Control/webview/**
            artifact: 'padv_artifacts_4'
            publishLocation: 'pipeline' 
          

        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/04_Results/InnerLoop_Control/webview/**
            artifact: 'padv_artifacts_5'
            publishLocation: 'pipeline' 
                        
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/04_Results/OuterLoop_Control/webview/**
            artifact: 'padv_artifacts_6'
            publishLocation: 'pipeline' 
            
            

