trigger:
- main

pool: default

jobs:
- job: CacheHelloFile
  displayName: 'Cache hello.txt'
  steps:
  - task: Cache@2
    displayName: 'Restore Cache'
    inputs:
      key: '"hello-cache" | "$(Agent.OS)"'
      path: $(Agent.BuildDirectory)/hello-cache
      cacheHitVar: CACHE_RESTORED 

  - script: |
      echo "$(CACHE_RESTORED)"
      if [ "$(CACHE_RESTORED)" != "true" ]; then
        mkdir $(Agent.BuildDirectory)/hello-cache
        echo "Hello, World!" > $(Agent.BuildDirectory)/hello-cache/hello.txt
        echo "true"
        echo "$(Agent.BuildDirectory)"
      else
        echo "false"
      fi
    displayName: 'Create hello.txt'

