trigger:
  branches:
    include:
      - main

stages:
- stage: Sample_Stage
  displayName: Sample Stage
  jobs:
  - job: Sample_Job
    pool: Default  
    steps:
     - script: |
            echo "SAMPLE STAGE FOR PARALLEL PIPELINE"
 
  

- stage: Merge_Test_Results_AHRS_Voter
  dependsOn: Sample_Stage 
  
  jobs:
  - job: Merge_Test_Results_AHRS_Voter
    displayName: 'Merge_Test_Results_AHRS_Voter'
    pool: Default
    
    steps:
        - checkout: self 
          displayName: 'Checkout Repository'
          
    
      
        - task: CmdLine@2
          displayName: 'Launch MATLAB'
          inputs:
            script: |
             mw -using bslcicd matlab -nodesktop -logfile output.log  -batch "openProject(pwd);[~,exitCode] = runprocess(Tasks = {'padv.builtin.task.MergeTestResults|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force = false, ExitInBatchMode = false, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true); exit(exitCode);" 
        
        - task: CopyFiles@2
          displayName: 'Move desired artifacts to "temp" folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
                    03_Code/**
                    04_Results/AHRS_Voter/code_inspection/**
                    04_Results/AHRS_Voter/code_quality/**
                    04_Results/AHRS_Voter/coding_standards/**
                    04_Results/AHRS_Voter/design_error_detections/**
                    04_Results/AHRS_Voter/model_comparison/**
                    04_Results/AHRS_Voter/model_standards_results/**
                    04_Results/AHRS_Voter/system_design_description/**
                    04_Results/AHRS_Voter/webview/**
                    04_Results/test_results/**
                    derived/artifacts.dmr
            targetFolder: $(System.DefaultWorkingDirectory)/temp/
        

