trigger:
  branches:
    include:
      - main

stages:
- stage: Generate_Simulink_Web_View
  jobs:
  - job: Generate_Simulink_Web_View
    displayName: 'Generate_Simulink_Web_View'
    pool: Default
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
        script: |
          mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx', 'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"

    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/04_Results/
        artifact: 'padv_artifacts_results1'
        publishLocation: 'pipeline' 
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/derived/
        artifact: 'padv_artifacts_derived1'
        publishLocation: 'pipeline'     

- stage: Check_Modeling_Standards 
  dependsOn: Generate_Simulink_Web_View            
  jobs:
  - job: Check_Modeling_Standards
    displayName: 'Check_Modeling_Standards'
    pool: Default
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Results Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_results1'
        targetPath: '$(System.DefaultWorkingDirectory)/04_Results'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Derived Artifact'
      inputs:
        buildType: 'current'
        artifactName: 'padv_artifacts_derived1'
        targetPath: '$(System.DefaultWorkingDirectory)/derived'

