trigger:
      - main

stages:
- stage: Generate_Simulink_Web_View
  jobs:
      - job: Generate_Simulink_Web_View
        pool: Default

        steps:
        - checkout: self
          displayName: 'Checkout Repository'

        - script: |
              # Create a cache_folder in $(System.DefaultWorkingDirectory)
              mkdir $(System.DefaultWorkingDirectory)/cache_folder
          displayName: 'Create Cache Folder'   


        - task: Cache@2
          displayName: Restore Cache2
          inputs:
            key: 'caching|$(Build.BuildId)'
            restoreKeys: 
                  padv_caches15
            path: |
                    $(System.DefaultWorkingDirectory)/cache_folder        
                                      
