trigger:
  branches:
    include:
      - main

stages:
- stage: Generate_Simulink_Web_View_Actuator_Control
  dependsOn: Sample_Stage
  
  jobs:
  - job: Generate_Simulink_Web_View_Actuator_Control
    displayName: 'Generate_Simulink_Web_View_Actuator_Control'
    pool: Default
    
    steps:
    - checkout: self
      displayName: 'Checkout Repository'
      
    - script: |
          # Create a cache_folder in $(System.DefaultWorkingDirectory)
          mkdir $(System.DefaultWorkingDirectory)/cache_folder
      displayName: 'Create Cache Folder'   
      
    - task: Cache@2
      displayName: Restore Cache
      inputs:
        key: 'ACT_11'  
        path: |
                $(System.DefaultWorkingDirectory)/cache_folder    
        cacheHitVar: CACHE_RESTORED      
        
    - task: Cache@2
      displayName: Restore Cache from last job
      inputs:
        key: ACT_22
        path: |
                $(System.DefaultWorkingDirectory)/cache_folder   
      condition: eq(variables.CACHE_RESTORED, 'true')   
      
    - task: CopyFiles@2
      displayName: 'Move cache to Respective Folders'
      inputs:
        sourceFolder: $(System.DefaultWorkingDirectory)/cache_folder
        contents: |
            derived/artifacts.dmr
            04_Results/Actuator_Control/webview/**
            04_Results/Actuator_Control/model_standards_results/**
            04_Results/Actuator_Control/design_error_detections/**
        targetFolder: $(System.DefaultWorkingDirectory)     
        
    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
        script: |
          mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);" 
   
    - task: CopyFiles@2
      displayName: 'Move desired artifacts to "cache_folder" folder'
      inputs:
        sourceFolder: $(System.DefaultWorkingDirectory)
        contents: |
            derived/artifacts.dmr
            04_Results/Actuator_Control/webview/**
            04_Results/Actuator_Control/model_standards_results/**
            04_Results/Actuator_Control/design_error_detections/**
        targetFolder: $(System.DefaultWorkingDirectory)/cache_folder/
        
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/cache_folder/
        artifact: ' Actuator_Control_padv_artifacts_first'
        publishLocation: 'pipeline' 


- stage: Check_Modeling_Standards_Actuator_Control
  dependsOn: Generate_Simulink_Web_View_Actuator_Control   
  
  jobs:
  - job: Check_Modeling_Standards_Actuator_Control
    displayName: 'Check_Modeling_Standards_Actuator_Control'
    pool: Default
    
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'
      
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifacts'
      inputs:
       artifactName: 'Actuator_Control_padv_artifacts_first'
       downloadPath: $(System.DefaultWorkingDirectory)/DownloadedArtifacts
       
    - task: CopyFiles@2
      displayName: 'Move Artifacts to Respective Folders'
      inputs:
        sourceFolder: $(System.DefaultWorkingDirectory)/DownloadedArtifacts
        contents: |
         derived/artifacts.dmr
         04_Results/Actuator_Control/webview/**
         04_Results/Actuator_Control/model_standards_results/**
         04_Results/Actuator_Control/design_error_detections/**
        targetFolder: $(System.DefaultWorkingDirectory)

    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
        script: |
         mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);" 
    
    - task: CopyFiles@2
      displayName: 'Move desired artifacts to "temp" folder'
      inputs:
        sourceFolder: $(System.DefaultWorkingDirectory)
        contents: |
            derived/artifacts.dmr
            04_Results/Actuator_Control/webview/**
            04_Results/Actuator_Control/model_standards_results/**
            04_Results/Actuator_Control/design_error_detections/**
        targetFolder: $(System.DefaultWorkingDirectory)/temp/
        
    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/temp/
        artifact: 'Actuator_Control_padv_artifacts_second'
        publishLocation: 'pipeline' 


- stage: Detect_Design_Errors_Actuator_Control
  dependsOn: Check_Modeling_Standards_Actuator_Control
  
  jobs:
  - job: Detect_Design_Errors_Actuator_Control
    displayName: 'Detect_Design_Errors_Actuator_Control'
    pool: Default
    
    steps:
    - checkout: self 
      displayName: 'Checkout Repository'   
      
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifacts'
      inputs:
       artifactName: 'Actuator_Control_padv_artifacts_second'
       downloadPath: $(System.DefaultWorkingDirectory)/DownloadedArtifacts1
       
    - task: CopyFiles@2
      displayName: 'Move Artifacts to Respective Folders'
      inputs:
       sourceFolder: $(System.DefaultWorkingDirectory)/DownloadedArtifacts1
       contents: |
            derived/artifacts.dmr
            04_Results/Actuator_Control/webview/**
            04_Results/Actuator_Control/model_standards_results/**
            04_Results/Actuator_Control/design_error_detections/**
       targetFolder: $(System.DefaultWorkingDirectory)

    - task: CmdLine@2
      displayName: 'Launch MATLAB'
      inputs:
       script: |
        mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);" 

    - task: CopyFiles@2
      displayName: 'move desired artifacts to "temp" folder'
      inputs:
        sourceFolder: $(System.DefaultWorkingDirectory)
        contents: |
         derived/artifacts.dmr
         04_Results/Actuator_Control/webview/**
         04_Results/Actuator_Control/model_standards_results/**
         04_Results/Actuator_Control/design_error_detections/**
        targetFolder: $(System.DefaultWorkingDirectory)/temp

    - task: PublishPipelineArtifact@1
      displayName: 'Upload Artifacts' 
      inputs:
       targetPath: $(System.DefaultWorkingDirectory)/temp/
       artifact: 'Actuator_Control_padv_artifacts'
       publishLocation: 'pipeline'  

    - task: CopyFiles@2
      displayName: 'Move Artifacts to Respective Folders'
      inputs:
       sourceFolder: $(System.DefaultWorkingDirectory)/temp
       contents: |
         derived/artifacts.dmr
         04_Results/Actuator_Control/webview/**
         04_Results/Actuator_Control/model_standards_results/**
         04_Results/Actuator_Control/design_error_detections/**
       targetFolder: $(System.DefaultWorkingDirectory)    
    
    - task: Cache@2
      displayName: Restore Cache
      inputs:
        key: ACT_22
        path: |
                $(System.DefaultWorkingDirectory)/temp




