trigger:
  branches:
    include:
      - main

stages:
- stage: Inspect_Code_InnerLoop_Control
  
  jobs:
  - job:  Inspect_Code_InnerLoop_Control
    displayName: ' Inspect_Code_InnerLoop_Control'
    pool: Default
    
    steps:
        - checkout: self 
          displayName: 'Checkout Repository'
            
        - task: CmdLine@2
          displayName: 'Launch MATLAB'
          inputs:
            script: |
             mw -using bslcicd matlab -nodesktop -logfile output.log -batch "openProject(pwd);[~,exitCode] = runprocess(Tasks = {'padv.builtin.task.RunCodeInspection|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx'}, Force = false, ExitInBatchMode = false, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true) ;exit(exitCode);" 

        - task: CopyFiles@2
          displayName: 'Move desired artifacts to "temp" folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
                    03_Code/**
                    04_Results/InnerLoop_Control/code_inspection/**
                    04_Results/InnerLoop_Control/code_quality/**
                    04_Results/InnerLoop_Control/coding_standards/**
                    04_Results/InnerLoop_Control/design_error_detections/**
                    04_Results/InnerLoop_Control/model_comparison/**
                    04_Results/InnerLoop_Control/model_standards_results/**
                    04_Results/InnerLoop_Control/system_design_description/**
                    04_Results/InnerLoop_Control/webview/**
                    04_Results/test_results/**
                    derived/artifacts.dmr
            targetFolder: $(System.DefaultWorkingDirectory)/temp/
        
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/temp/
            artifact: 'InnerLoop_Control_padv_artifacts_8'
            publishLocation: 'pipeline' 

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: |
                padv_builtin_task_RunCodeInspection_InnerLoop_Control_JUnit.xml
            searchFolder: '$(System.DefaultWorkingDirectory)/04_Results/junit'