trigger:
- main

pool: default

jobs:
- job: CacheHelloFile
  displayName: 'Cache hello.txt'
  steps:
  - task: Cache@2
    displayName: 'Restore Cache'
    inputs:
      key: 'hello-filesss | "$(Agent.OS)" | test.txt'
      path: $(Agent.BuildDirectory)
      cacheHitVar: 'CacheRestored'

  - script: |
      if [ "$(CacheRestored)" != "true" ]; then
        mkdir $(Agent.BuildDirectory)/hello-cache
        echo "$(Agent.BuildDirectory)"
        echo "Hello, World!" > $(Agent.BuildDirectory)/hello-cache/hello.txt
      fi
    displayName: 'Create hello.txt'

