trigger:
  branches:
    include:
      - main

stages:
- stage: Generate_Simulink_Web_View

  jobs:
  - job: Generate_Simulink_Web_View
    pool:
     vmImage: 'ubuntu-latest'

    steps:
        - checkout: self
          displayName: 'Checkout Repository'

        - checkout: self
          displayName: 'Checkout Repository2' 

  - job: Generate_Simulink_Web_View_second
    pool:
     vmImage: 'ubuntu-latest'

    steps:
        - checkout: self
          displayName: 'Checkout Repository'        

- stage: Check_Modelling

  jobs:
  - job: Check_Modeling
    pool:
     vmImage: 'ubuntu-latest'

    steps:
        - checkout: self
          displayName: 'Checkout Repository'          