trigger:
  - main

stages:
  - stage: 
      Generate_Simulink_Web_View
    condition: 
      succeededOrFailed()
    jobs:
      - job: 
          Generate_Simulink_Web_View
        displayName: 
          'Generate_Simulink_Web_View'
        pool: 
          Default

        steps:

            - script: |
                  # Create a cache_folder in $(System.DefaultWorkingDirectory)
                  mkdir $(System.DefaultWorkingDirectory)/cache_folder
              displayName: 'Create Cache Folder'   
        

      