trigger:
- main

pool: default

jobs:
- job: CacheHelloFile
  displayName: 'Cache hello.txt'
  steps:
  - task: Cache@2
    displayName: 'Restore Cache'
    inputs:
      key: 'hello-file | "$(Agent.OS)"'
      path: $(Agent.BuildDirectory)/hello-cache
      cacheHitVar: 'CacheRestored'

  - script: |
      if [ "$(CacheRestored)" != "true" ]; then
        mkdir $(Agent.BuildDirectory)/hello-cache
        echo "Hello, World!" > $(Agent.BuildDirectory)/hello-cache/hello.txt
        echo "##vso[task.setvariable variable=CacheRestored]true"
      else
        echo "##vso[task.setvariable variable=CacheRestored]false"
      fi
    displayName: 'Create hello.txt'

  - task: Cache@2
    displayName: 'Cache hello.txt'
    inputs:
      key: 'hello-file | "$(Agent.OS)"'
      path: $(Agent.BuildDirectory)/hello-cache
