trigger:
  branches:
    include:
      - main



stages:
- stage: A

  jobs:
  - job: A
    displayName: 'A'
    pool: Default

    steps: 
      - script: |
          echo "A"
        displayName: 'Echo '
     

- stage: B
  dependsOn: A
  jobs:
  - job: B
    displayName: 'B'
    pool: Default

    steps:
        - script: |
            echo "B"
          displayName: 'Echo ' 
    
- stage: C
  dependsOn: A
  jobs:
  - job: C
    displayName: 'C'
    pool: Default

    steps:
        - script: |
            echo "C"
          displayName: 'Echo' 
        
- stage: D
  dependsOn: A
  jobs:
  - job: D
    displayName: 'D'
    pool: Default

    steps:
        - script: |
            echo "D"
          displayName: 'Echo' 
        
      
- stage: E
  dependsOn: B
  jobs:
  - job: B
    displayName: 'B'
    pool: Default

    steps:
        - script: |
            echo "E"
          displayName: 'Echo' 

- stage: F
  dependsOn: C
  jobs:
  - job: F
    displayName: 'F'
    pool: Default

    steps:
        - script: |
            echo "F"
          displayName: 'Echo' 
        
      
- stage: G
  dependsOn:
   - D
   - C
  jobs:
  - job: G
    displayName: 'G'
    pool: Default

    steps:
        - script: |
            echo "G"
          displayName: 'Echo' 
  
- stage: H
  dependsOn:
   - E
   - F
  jobs:
  - job: H
    displayName: 'H'
    pool: Default

    steps:
        - script: |
            echo "H"
          displayName: 'Echo' 