trigger:
  branches:
    include:
      - main

stages:
- stage: Check_Modeling_Standards 
  
  jobs:
  - job: Check_Modeling_Standards
    displayName: 'Check_Modeling_Standards'
    pool: Default

    steps:
        - checkout: self 
          displayName: 'Checkout Repository'

        - task: CmdLine@2
          inputs:
            script: |
              echo Write your commands here
              set

        - task: RunMATLABCommand@0
          inputs:
            command: "openProject(pwd);runprocess(Tasks = {''padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'', ''padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx'', ''padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx'', ''padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx'', ''padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx''}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"
            startupOptions: '-nodesktop -logfile output.log'

        
        - task: CopyFiles@2
          displayName: 'Move desired artifacts to "temp" folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
                    04_Results/AHRS_Voter/model_standards_results/**
                    04_Results/Actuator_Control/model_standards_results/**
                    04_Results/Flight_Control/model_standards_results/**
                    04_Results/InnerLoop_Control/model_standards_results/**
                    04_Results/OuterLoop_Control/model_standards_results/**
                    derived/artifacts.dmr
            targetFolder: $(System.DefaultWorkingDirectory)/temp/
          condition: succeededOrFailed()   
        
        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/temp/
            artifact: 'Check_Modeling_Standards_padv_artifacts'
            publishLocation: 'pipeline' 
          condition: succeededOrFailed()    

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: |
                padv_builtin_task_RunModelStandards_Actuator_Control_JUnit.xml
                padv_builtin_task_RunModelStandards_AHRS_Voter_JUnit.xml
                padv_builtin_task_RunModelStandards_Flight_Control_JUnit.xml
                padv_builtin_task_RunModelStandards_InnerLoop_Control_JUnit.xml
                padv_builtin_task_RunModelStandards_OuterLoop_Control_JUnit.xml
            searchFolder: '$(System.DefaultWorkingDirectory)/04_Results/junit'
          condition: succeededOrFailed()  
  