trigger:
  branches:
    include:
      - main



stages:
- stage: Generating_Pipeline

  jobs:
  - job: Generating_Pipeline
    displayName: 'Generate Pipeline'
    pool: Default

    steps:
        - checkout: self
          displayName: 'Checkout Repository'  

        - bash: |
            cp azure-pipelines.yaml abc.yaml
          displayName: 'Copy YAML content'
          workingDirectory: $(Build.SourcesDirectory) 

        - task: PublishPipelineArtifact@1
          displayName: 'Upload Artifacts' 
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/abc.yaml
            artifact: 'artifacts_1'
            publishLocation: 'pipeline'   
  

- stage: Executing_Pipeline

  jobs:
  - job: Executing_Pipeline
    displayName: 'Execute Pipeline'
    pool: Default

    steps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifacts'
          inputs:
           artifactName: 'artifacts_1'
           downloadPath: $(System.DefaultWorkingDirectory)/DownloadedArtifacts

        - template: abc.yml      