trigger:
  branches:
    include:
      - main

stages:
- stage: Generate_Simulink_Web_View

  jobs:
  - job: Generate_Simulink_Web_View
    displayName: 'Generate_Simulink_Web_View'
    pool: Default

    steps:
        - checkout: self
          displayName: 'Checkout Repository'

        - script: |
              mkdir -p "$(System.DefaultWorkingDirectory)/temp"
              echo "Created a new 'temp' folder in $(System.DefaultWorkingDirectory)."
          displayName: 'Create Temp Folder in Default Working Directory'
          
        - script: |
            echo "Hello World" > $(System.DefaultWorkingDirectory)/temp/hello_world.txt
            echo "Created hello_world.txt in the temp directory."
          displayName: 'Create Hello World Text File'

        - task: CopyFiles@2
          displayName: 'Move "temp" to network folder'
          inputs:
            sourceFolder: $(System.DefaultWorkingDirectory)
            contents: |
               temp/**
            targetFolder: /mathworks/devel/sandbox/vandita/
      


- stage: Check_Modeling_Standards 
  dependsOn: Generate_Simulink_Web_View
   
  
  jobs:
  - job: Check_Modeling_Standards
    displayName: 'Check_Modeling_Standards'
    pool: Default

    steps:
        - checkout: self 
          displayName: 'Checkout Repository'
          
        - task: CopyFiles@2
          displayName: 'Move "temp" from network folder'
          inputs:
            sourceFolder: /mathworks/devel/sandbox/vandita/temp/
            contents: |
                hello_world.txt
            targetFolder: $(System.DefaultWorkingDirectory)
           
        
        
       